// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_J-8GXGNZC6RMf0eoLy6PddzOei4gjA',
    appId: '1:647471734749:web:95b1edd66c74500b0f6034',
    messagingSenderId: '647471734749',
    projectId: 'receipt-recognizer-369212',
    authDomain: 'receipt-recognizer-369212.firebaseapp.com',
    storageBucket: 'receipt-recognizer-369212.appspot.com',
    measurementId: 'G-BWDTKJ55QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-P1bJJF9XZrMCRyyuTcZhab8GlY_As4',
    appId: '1:647471734749:android:9578823f2f16f7570f6034',
    messagingSenderId: '647471734749',
    projectId: 'receipt-recognizer-369212',
    storageBucket: 'receipt-recognizer-369212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEx9Opkdr_WYl8kr8ss1VNAAzVf3CDKUs',
    appId: '1:647471734749:ios:fc7fa505c28c4ce80f6034',
    messagingSenderId: '647471734749',
    projectId: 'receipt-recognizer-369212',
    storageBucket: 'receipt-recognizer-369212.appspot.com',
    iosClientId: '647471734749-4i4hftheppp1lhi0istjpmih8g68s1jn.apps.googleusercontent.com',
    iosBundleId: 'NV6UVHBAEJ.receiptRecognizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEx9Opkdr_WYl8kr8ss1VNAAzVf3CDKUs',
    appId: '1:647471734749:ios:93d776ce014258860f6034',
    messagingSenderId: '647471734749',
    projectId: 'receipt-recognizer-369212',
    storageBucket: 'receipt-recognizer-369212.appspot.com',
    iosClientId: '647471734749-ntm48bc2cujp8bh1ns5i6n22lfpkbk2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptRecognizer',
  );
}
